package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'S3storage_S3Storage'
in the project with id = 'S3storage', and delete the patch script.
*/
create(RelativeId("S3storage"), BuildType({
    id("S3storage_S3Storage")
    name = "s3Storage"

    vcs {
        cleanCheckout = true
    }

    steps {
        script {
            scriptContent = "rm -rf %system.agent.home.dir%/system/.artifacts_cache"
        }
        script {
            name = "art1"
            enabled = false
            scriptContent = """
                mkfile 1g a
                echo "##teamcity[publishArtifacts 'a']"
            """.trimIndent()
        }
        script {
            name = "art2"
            scriptContent = """
                for j in ${'$'}(seq 1 1 50)
                do
                	mkfile 1m file${'$'}j
                    echo "##teamcity[publishArtifacts 'file${'$'}j']"
                done
            """.trimIndent()
        }
        script {
            name = "art3"
            enabled = false
            scriptContent = """
                mkfile 1m 1.txt
                mkfile 1m 2.txt
                
                echo "##teamcity[publishArtifacts '*.txt']"
                mkdir dir
                for j in ${'$'}(seq 1 1 10000)
                do
                	echo a > ${'$'}j.bat
                    echo a > dir/${'$'}j.cmd
                    
                done
                echo "##teamcity[publishArtifacts 'dir/**']"
                echo "##teamcity[publishArtifacts '*.bat']"
            """.trimIndent()
        }
    }
}))

