package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.S3Storage
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.s3Storage
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<S3Storage> {
            s3Storage {
                id = "PROJECT_EXT_72"
                storageName = "s3multipart"
                bucketName = "chubatovatransferacceleration"
                bucketPrefix = "multipart_test"
                multipartThreshold = "200MB"
                multipartChunksize = "200MB"
                accessKey = "credentialsJSON:e5ec9cb3-17dc-4be1-85fe-6d3b98bc961a"
                awsEnvironment = default {
                    awsRegionName = "eu-central-1"
                }
                accessKeyID = "AKIA5JH2VERVHVMPJQJI"
            }
        }
        feature1.apply {
            param("storage.s3.acl", "")
        }
    }
}
